package com.java.pojo;
// Generated 2018-11-19 15:53:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Lodginginfo generated by hbm2java
 */
public class Lodginginfo implements java.io.Serializable {

	private int id;
	private Date entryDate;
	private Date leaveDate;
	private Integer days;
	private String roomId;
	private Integer deposit;
	private String reservationId;
	private String operatorId;
	private Date createDate;

	public Lodginginfo() {
	}

	public Lodginginfo(int id) {
		this.id = id;
	}

	public Lodginginfo(int id, Date entryDate, Date leaveDate, Integer days, String roomId, Integer deposit,
			String reservationId, String operatorId, Date createDate) {
		this.id = id;
		this.entryDate = entryDate;
		this.leaveDate = leaveDate;
		this.days = days;
		this.roomId = roomId;
		this.deposit = deposit;
		this.reservationId = reservationId;
		this.operatorId = operatorId;
		this.createDate = createDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getLeaveDate() {
		return this.leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	public Integer getDays() {
		return this.days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public Integer getDeposit() {
		return this.deposit;
	}

	public void setDeposit(Integer deposit) {
		this.deposit = deposit;
	}

	public String getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(String reservationId) {
		this.reservationId = reservationId;
	}

	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
