package com.java.pojo;
// Generated 2018-11-19 15:53:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

	private int id;
	private String typeId;
	private Integer floor;
	private String status;
	private Date updateDate;
	private Date createDate;

	public Room() {
	}

	public Room(int id) {
		this.id = id;
	}

	public Room(int id, String typeId, Integer floor, String status, Date updateDate, Date createDate) {
		this.id = id;
		this.typeId = typeId;
		this.floor = floor;
		this.status = status;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
