package com.java.pojo;
// Generated 2018-11-19 15:54:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer id;
	private String menuName;
	private Integer locked;
	private String descript;
	private Set menuitems = new HashSet(0);

	public Menu() {
	}

	public Menu(String menuName, Integer locked, String descript, Set menuitems) {
		this.menuName = menuName;
		this.locked = locked;
		this.descript = descript;
		this.menuitems = menuitems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getLocked() {
		return this.locked;
	}

	public void setLocked(Integer locked) {
		this.locked = locked;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public Set getMenuitems() {
		return this.menuitems;
	}

	public void setMenuitems(Set menuitems) {
		this.menuitems = menuitems;
	}

}
