package com.java.pojo;
// Generated 2018-11-19 15:54:28 by Hibernate Tools 3.4.0.CR1

/**
 * Roleitem generated by hbm2java
 */
public class Roleitem implements java.io.Serializable {

	private int id;
	private String roleId;
	private Integer itemId;

	public Roleitem() {
	}

	public Roleitem(int id) {
		this.id = id;
	}

	public Roleitem(int id, String roleId, Integer itemId) {
		this.id = id;
		this.roleId = roleId;
		this.itemId = itemId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

}
