package com.java.pojo;
// Generated 2018-11-19 15:54:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Roomtype generated by hbm2java
 */
public class Roomtype implements java.io.Serializable {

	private Integer id;
	private String typeName;
	private Float dayPrice;
	private Float hourPrice;
	private Date updateDate;
	private Date createDate;

	public Roomtype() {
	}

	public Roomtype(String typeName, Float dayPrice, Float hourPrice, Date updateDate, Date createDate) {
		this.typeName = typeName;
		this.dayPrice = dayPrice;
		this.hourPrice = hourPrice;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Float getDayPrice() {
		return this.dayPrice;
	}

	public void setDayPrice(Float dayPrice) {
		this.dayPrice = dayPrice;
	}

	public Float getHourPrice() {
		return this.hourPrice;
	}

	public void setHourPrice(Float hourPrice) {
		this.hourPrice = hourPrice;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
